### ISSUE TITLE
Update to nom 7

### ISSUE THREAD

**Issue by sdroege** [rutgersc/m3u8-rs#35]
Currently this crate still depends on nom 5. Updating will take a bit of effort though because nom 7 finally got rid of the macro based parser combinators, which are still in use here.

**Comment by sdroege** [comment]
I might take a look at this some time this week, it's not a lot of code and there are tests

**Comment by sdroege** [comment]
Yeah, easier than expected. I'm half-way through

**Comment by rutgersc** [comment]
Exactly, I get reminded of this whenever i'm touching the codebase. The macro's make writing and debugging really cumbersome compared to normal functions. Been putting it off because of a lack of free time, so thank you for taking a look!

One thing I had in mind, besides relying only on the tests, was to use a version of nom that contains both the macros and the functions. That way the output of the rewritten macros can be compared 1-to-1 to the existing implementation, as an easy way to guarantee the same behavior.
